DROP TABLE IF EXISTS user_device;
DROP TABLE IF EXISTS users;

DROP DOMAIN IF EXISTS user_status;
DROP DOMAIN IF EXISTS platform_type;

CREATE DOMAIN user_status AS VARCHAR(32);
CREATE DOMAIN platform_type AS VARCHAR(32);

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT RANDOM_UUID(),
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    status user_status NOT NULL,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_device (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT RANDOM_UUID(),
    user_id INT NOT NULL,
    device_id VARCHAR(128) NOT NULL,
    platform platform_type NOT NULL,
    push_token VARCHAR(255),
    is_push_enabled BOOLEAN NOT NULL,
    last_activate_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_device_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_device_user_and_device UNIQUE (user_id, device_id)
);
